# The KubeLogExporter cron job needs to fulfil the following requirements:
#    It needs to run every 5 minutes
#    It needs to be successful, e.g. no error when reading or storing a log occurs
#    It needs the use a service account to have the proper access rights to namespaces, pods and logs
#    It needs to use a persistent volume to store the log files, so that independent of the actual node where the job runs the same log files are amended

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-log-exporter-cron
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          serviceAccountName: log-exporter-sa
          containers:
            - name: kube-log-exporter
              image: docker.admantium.com/kube-log-exporter:0.1.9.12
              args: ['node', 'cluster.js']
              volumeMounts:
                - name: log-exporter-volume
                  mountPath: /etc/kube-log-exporter/logs
          restartPolicy: Never
          volumes:
            - name: log-exporter-volume
              persistentVolumeClaim:
                claimName: log-exporter-pvc
          imagePullSecrets:
            - name: registry-secret
