apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nvidia-smi
  namespace: my-cronjob
  labels:
    app: my-nvidia-smi-cronjob
data:   
  nvidia-smi: |
    #!/bin/bash  
    export NVIDIA_CUDA_IMG="nvidia/cuda" \
    && export NVIDIA_CUDA_IMG_TAG="11.6.2-base-ubuntu20.04" \
    && export NVIDIA_QUERY_GPU="timestamp,serial,name,mig.mode.current,utilization.gpu,memory.total,memory.used,utilization.memory" \
    && export NVIDIA_FORMAT="csv,nounits,noheader" \
    && export NVIDIA_SMI_QUERY_OUTPUT="$(nvidia-smi --query-gpu=${NVIDIA_QUERY_GPU} --format=${NVIDIA_FORMAT})" \
    && echo $NVIDIA_SMI_QUERY_OUTPUT