apiVersion: batch/v1
kind: CronJob
metadata:
  name: nvidia-smi-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nvidia-cuda
            image: nvidia/cuda:11.6.2-base-ubuntu20.04
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - "nvidia-smi --query-gpu='timestamp,serial,name,mig.mode.current,utilization.gpu,memory.total,memory.used,utilization.memory' --format='csv,nounits,noheader'"
          restartPolicy: OnFailure